### ISSUE TITLE
[Bug]: Creation of compute Instances (and others) fails with `SetNew only operates on computed keys`

### ISSUE THREAD

**Issue by JonathanO** [crossplane-contrib/provider-upjet-gcp#472]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

* compute.gcp.upbound.io/v1beta1 - Instance
* cloudscheduler.gcp.upbound.io/v1beta1 - Job

### Resource MRs required to reproduce the bug

examples/compute/instance.yaml
examples/cloudscheduler/job.yaml

### Steps to Reproduce

Apply examples/compute/instance.yaml (or examples/cloudscheduler/job.yaml)

### What happened?

External resource was not created, reconciliation fails with an error from terraform:
`observe failed: cannot compute the instance diff: failed to get *terraform.InstanceDiff: SetNew only operates on computed keys - zone is not one`
(For Job it's `... - region is not one`)

### Crossplane Version

1.15.0

### Provider Version

1.0.0

### Additional Info

The failing calls to SetNew appear to have been introduced in https://github.com/GoogleCloudPlatform/magic-modules/pull/8569

**Comment by turkenf** [comment]
Hi @JonathanO,

Thank you for bringing up this issue, I can reproduce the issue with the provided information.
- For `Instance.compute.gcp.upbound.io/v1beta1`:
```
  - lastTransitionTime: "2024-03-11T21:07:55Z"
    message: 'observe failed: cannot compute the instance diff: failed to get *terraform.InstanceDiff:
      SetNew only operates on computed keys - zone is not one'
    reason: ReconcileError
    status: "False"
    type: Synced
```
- For `Job.cloudscheduler.gcp.upbound.io/v1beta1`:
```
  - lastTransitionTime: "2024-03-11T21:16:22Z"
    message: 'observe failed: cannot compute the instance diff: failed to get *terraform.InstanceDiff:
      SetNew only operates on computed keys - region is not one'
    reason: ReconcileError
    status: "False"
    type: Synced
```

**Comment by selfuryon** [comment]
For already created resources it's the same:
```
Events:                                                                                                                                                                                                          
  Type     Reason                         Age                 From                                                   Message                                                                                     
  ----     ------                         ----                ----                                                   -------                                                                                     
  Warning  CannotObserveExternalResource  27s (x36 over 30m)  managed/compute.gcp.upbound.io/v1beta1, kind=instance  cannot compute the instance diff: failed to get *terraform.InstanceDiff: SetNew only operate
s on computed keys - zone is not one    
```

I faced with the problem on these resources:
* instance.compute.gcp.upbound.io
* instancegroup.compute.gcp.upbound.io

**Comment by ulucinar** [comment]
We have investigated the root cause of this issue with @sergenyalcin. upjet's [`config.MarkAsRequired`](https://github.com/crossplane/upjet/blob/50919febc5ab73b58020533d616a3d37227aff92/pkg/config/common.go#L139) works by manipulating the native Terraform schema of a resource as follows:
```go
func MarkAsRequired(sch *schema.Resource, fieldpaths ...string) {
	for _, fieldpath := range fieldpaths {
		if s := GetSchema(sch, fieldpath); s != nil {
			s.Computed = false
			s.Optional = false
		}
	}
}
```

Setting `schema.Schema.Computed` and `schema.Schema.Optional` forces the corresponding field in the generated CRD to be a required field because upjet's code generation pipelines check these two properties when deciding whether a field in the generated CRD should be a required field. 

It turns out that interfering with the native schema has adverse affects here. The GCP [project](https://github.com/hashicorp/terraform-provider-google/blob/0d57f75575b997e1cc26e23819ca6a1e43178997/google/tpgresource/utils.go#L769) and [zone](https://github.com/hashicorp/terraform-provider-google/blob/0d57f75575b997e1cc26e23819ca6a1e43178997/google/tpgresource/utils.go#L809) defaulting functions [introduced](https://github.com/hashicorp/terraform-provider-google/blob/0d57f75575b997e1cc26e23819ca6a1e43178997/google/services/compute/resource_compute_instance.go#L1059) as `CustomizeDiff` functions in the Terraform resource make calls to the `schema.ResourceDiff.SetNew`, which in turn [asserts the schema of the attribute being set so that it's a computed value](https://github.com/hashicorp/terraform-plugin-sdk/blob/be3b2d013efe72796bed19b25955bea10d3f8351/helper/schema/resource_diff.go#L618). 

However, `MarkAsRequired`'s modification on the native schema breaks this check and results in the error message reported in this issue. These defaulting `CustomizeDiff` functions were not being used in the previous Terraform provider version we consumed (`v4.77.0`) before the `v1.0.0` release bumped it to `v5.19.0`. So, these bugs silently creeped in with the `v1.0.0` release, and are especially dangerous.

We had better get rid of all the Terraform schema modifications as they can potentially cause harmful interference with the Terraform runtime like this issue demonstrates. We have plans to remove the Terraform plugin SDK from upjet's code generation pipelines, which will enforce this. Till then, we must be very careful (and avoid as much as possible) modifying the Terraform schema for managed resource configuration.
